#!/bin/bash
# Script to update Vercel environment variables with new database connection

echo "🔧 Updating Vercel environment variables..."
echo ""
echo "⚠️  You need to update these in Vercel Dashboard:"
echo "https://vercel.com/james-projects-3eb6261c/brain-capture-prod/settings/environment-variables"
echo ""
echo "Update the following variables (Production environment):"
echo ""
echo "PGHOST:"
echo "  Old: my-brain-capture.cluster-c4vyo86kug4b.us-east-1.rds.amazonaws.com"
echo "  New: brain-capture.cluster-c4vyo86kug4b.us-east-1.rds.amazonaws.com"
echo ""
echo "AWS_RESOURCE_ARN:"
echo "  Old: arn:aws:rds:us-east-1:085597560799:cluster:my-brain-capture"
echo "  New: arn:aws:rds:us-east-1:085597560799:cluster:brain-capture"
echo ""
echo "AWS_ROLE_ARN:"
echo "  Old: arn:aws:iam::085597560799:role/Vercel/access-my-brain-capture"
echo "  New: arn:aws:iam::085597560799:role/Vercel/access-brain-capture"
echo ""
echo "✅ Other variables remain the same:"
echo "   - AWS_ACCOUNT_ID: 085597560799"
echo "   - AWS_REGION: us-east-1"
echo "   - PGDATABASE: postgres"
echo "   - PGPORT: 5432"
echo "   - PGSSLMODE: require"
echo "   - PGUSER: postgres"
echo ""
echo "📝 Steps:"
echo "1. Open the Vercel Dashboard link above"
echo "2. Click 'Edit' on PGHOST and update to: brain-capture.cluster-c4vyo86kug4b.us-east-1.rds.amazonaws.com"
echo "3. Click 'Edit' on AWS_RESOURCE_ARN and update to: arn:aws:rds:us-east-1:085597560799:cluster:brain-capture"
echo "4. Click 'Edit' on AWS_ROLE_ARN and update to: arn:aws:iam::085597560799:role/Vercel/access-brain-capture"
echo "5. Redeploy: vercel --prod"
